---
- id: CVE-2017-18342 # https://msg.pyyaml.org/load
  name: Disallow pyyaml.load
  entry: '\b(py)?yaml.load\b'
  language: pygrep
  files: '\.py$'

- id: remove-unicode-non-breaking-spaces
  name: Remove unicode non-breaking space character U+00A0
  language: system
  entry: perl -pi* -e 's/\xc2\xa0/ /g && ($t = 1) && print STDERR $_; END{{exit $t}}'
  exclude_types: [binary]

- id: remove-unicode-zero-width-space
  name: Remove unicode zero width space character U+200B
  language: system
  entry: perl -pi -e 's/\xe2\x80\x8b//g && ($t = 1) && print STDERR $_; END{{exit $t}}'
  exclude_types: [binary]

- id: remove-unicode-zero-width-non-breaking-spaces
  name: Remove unicode zero width non-breaking space character U+FEFF
  language: system
  entry: perl -pi* -e 's/\xef\xbb\xbf//g && ($t = 1) && print STDERR $_; END{{exit $t}}'
  exclude_types: [binary]

- id: remove-en-dashes
  name: Remove the unicode character U+2013 (en dash)
  language: system
  entry: perl -pi* -e 's/\xe2\x80\x93/-/g && ($t = 1) && print STDERR $_; END{{exit $t}}'
  exclude_types: [binary]

- id: sort-gitignore
  name: Sort contents of .gitignore
  language: script
  entry: "scripts/sort.sh"
  files: '.gitignore'

- id: sort-ansible-requirements-yml
  name: sort ansible requirements.yml files
  entry: scripts/sort-ansible-requirements-yml.py
  language: script
  files: '(^|\/)requirements\.ya?ml$'
